#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.local"
PERSIST_ROOT="$PROJECT_ROOT/.persist"
SECRETS_DIR="$PERSIST_ROOT/secrets"
SECRETS_ENV="$SECRETS_DIR/env.sh"
SNIPPET_START="# >>> ai-forecasting-hackathon env >>>"
SNIPPET_END="# <<< ai-forecasting-hackathon env <<<"

guard_agents_md() {
  if git -C "$PROJECT_ROOT" diff --quiet -- AGENTS.md; then
    return 0
  fi

  cat >&2 <<'EOF'
[post-start] WARNING: AGENTS.md is owner-controlled. Detected local edits—revert them or wait for explicit owner instructions. Proceeding anyway.
EOF
}

ensure_snippet() {
  local rc_file="$1"
  if [ ! -f "$rc_file" ]; then
    return 0
  fi
  if [ ! -w "$rc_file" ]; then
    echo "[post-start] cannot modify $rc_file; skipping snippet" >&2
    return 0
  fi

  if grep -Fq "$SNIPPET_START" "$rc_file" >/dev/null 2>&1; then
    return 0
  fi

  if ! {
    printf "\n%s\n" "$SNIPPET_START"
    printf 'if [ -f "%s/.env.local" ]; then\n' "$PROJECT_ROOT"
    printf "  set -a\n"
    printf '  . "%s/.env.local"\n' "$PROJECT_ROOT"
    printf "  set +a\n"
    printf "fi\n"
    printf "%s\n" "$SNIPPET_END"
  } >>"$rc_file" 2>/dev/null; then
    echo "[post-start] could not append snippet to $rc_file" >&2
  fi
}

load_env_from_file() {
  local file="$1"
  if [ ! -f "$file" ]; then
    return 1
  fi
  if grep -Fq "PLACEHOLDER" "$file" >/dev/null 2>&1; then
    echo "[post-start] .env.local contains placeholder values; skipping auto-export" >&2
    return 1
  fi

  set -a
  # shellcheck disable=SC1090
  . "$file"
  set +a
}

write_env_exports() {
  mkdir -p "$SECRETS_DIR"
  {
    echo "#!/usr/bin/env bash"
    echo "# Autogenerated by scripts/post-start.sh"
    for var in GEMINI_API_KEY TAVILY_API_KEY; do
      local value="${!var:-}"
      if [ -n "$value" ]; then
        printf "export %s=%q\n" "$var" "$value"
      fi
    done
  } >"$SECRETS_ENV"
  chmod 600 "$SECRETS_ENV" || true
}

main() {
  guard_agents_md
  ensure_snippet "$HOME/.bashrc"
  ensure_snippet "$HOME/.zshrc"
  ensure_snippet "$HOME/.profile"

  if load_env_from_file "$ENV_FILE"; then
    write_env_exports
  fi
}

main "$@"
